ItemEvents.modifyTooltips(event => {
    // Han, you can copy the full line ["chemica:cyclohexane_bucket", "C₆H₁₂", "Cyclic hydrocarbon"], and add more chemicals to the list below. 
    // Just make sure to follow the same format: [item_id, chemical_formula, category]. Don't change anything else
    // I hope you have installed mods from Mods.md
    // In game, press F3+H to enable advanced tooltips.
    // There are creative tabs on top right of the inventory, select the chemica tab, it will help you find the buckets/tanks more easily.
    // The bucket id will be shown in grey colour when you hover over the item. 
    // REMEMBER - The display name and id are different. You need to use the id for the code, not the display name. 
    // For example, the display name of "chemica:cyclohexane_bucket" is "Cyclohexane Bucket". If you use the display name in the code, it won't work.
    const chemicals = [
        ["chemica:cyclohexane_bucket", "C₆H₁₂", "Cyclic hydrocarbon"],
        ["chemica:acetone_bucket","C₃H₆O","Ketone"],
        ["chemica:acrylonitrile_bucket", "C₃H₃N", "Nitrile"],
        ["chemica:adipic_acid_solution_bucket", "C₆H₁₀O₄", "Dicarboxylic Acid"],
        ["chemica:amine_catalyst_bucket","C₆H₁₂N₂","Tertiary Amine"],
        ["chemica:aromatic_mix_bucket","","Aromatic Hydrocarbons"],
        ["chemica:benzene_bucket","C₆H₆","Aromatic Hydrocarbon"],
        ["chemica:brine_bucket","NaCl","Inorganic Salt"],
        ["chemica:caustic_soda_bucket","NaOH","Inorganic Base"],
        ["chemica:cumene_bucket","C₉H₁₂","Aromatic Hydrocarbon"],
        ["chemica:cyclohexanol_bucket","C₆H₁₂O","Cyclic Alcohol"],
        ["chemica:distilled_water_bucket","H₂O","Inorganic Compound"],
        ["chemica:epoxy_precursor_bucket","C₃H₅ClO","Epoxide"],
        ["chemica:epoxy_resin_bucket","C₂₁H₂₄O₄","Glycidyl Ether"],
        ["chemica:ethylbenzene_bucket","C₈H₁₀","Aromatic Hydrocarbon"],
        ["chemica:ethyl_tert_butyl_ether_bucket","C₆H₁₄O","Ether"],
        ["chemica:gasoline_additive_mix_bucket","C₇H₈","Aromatic Hydrocarbon"],
        ["chemica:glycerin_bucket","C₃H₈O₃","Polyol"],
        ["chemica:hexamethylenediamine_solution_bucket","C₆H₁₆N₂","Diamine"],
        ["chemica:liquid_hydrogen_bucket","H₂","Nonmetal"],
        ["chemica:mercury_bucket","Hg","Transition Metal"],
        ["chemica:nitroglycerin_bucket","C₃H₅N₃O₉","Organic Nitrate"],
        ["chemica:pan_precursor_bucket","C₃H₃N","Nitrile"],
        ["chemica:phenol_bucket","C₆H₅OH","Phenol"],
        ["chemica:platinum_catalyst_carrier_bucket","Al₂O₃","Metal Oxide"],
        ["chemica:polyethylene_bucket","C₂H₄","Polymeric Hydrocarbon"],
        ["chemica:polyvinyl_chloride_bucket","C₂H₃Cl","Vinyl Polymer"],
        ["chemica:seed_oil_bucket","C₅₇H₁₁₀O₆","Triglyceride"],
        ["chemica:sucrose_solution_bucket","C₁₂H₂₂O₁₁","Disaccharide"],
        ["chemica:solder_solution_bucket","Ag + C₂₁H₂₄O₄","Conductive Adhesive"],
        ["chemica:tetraethyllead_bucket","C₈H₂₀Pb","Organometallic Compound"],
        ["chemica:titanium_tetrachloride_bucket","TiCl₄","Metal Halide"],
        ["chemica:toluene_bucket","C₇H₈","Aromatic Hydrocarbon"],
        ["chemica:waste_slurry_bucket","","Industrial Waste"],
        ["chemica:xylene_bucket","C₈H₁₀","Aromatic Hydrocarbon"],
        ["chemica:chromic_acid_bucket","H₂CrO₄","Inorganic Acid"],
        ["chemica:hydrochloric_acid_bucket","HCl","Inorganic Acid"],
        ["chemica:hydrofluoric_acid_bucket","HF","Inorganic Acid"],
        ["chemica:nitric_acid_bucket","HNO₃","Inorganic Acid"],
        ["chemica:phosphoric_acid_bucket","H₃PO₄","Inorganic Acid"],
        ["chemica:sulfuric_nickel_solution_bucket","NiSO₄","Inorganic Salt"],
        ["chemica:molten_glass_bucket","SiO₂","Amorphous Solid"],
        ["chemica:molten_nylon_bucket","C₁₂H₂₀N₂O₂","Polyamide"],
        ["chemica:molten_titanium_bucket","Ti","Transition Metal"],
        ["chemica:molten_tungsten_carbide_bucket","WC","Refractory Ceramic"],
        ["chemica:ammonia_bucket","NH₃","Inorganic Base"],
        ["chemica:argon_bucket","Ar","Noble Gas"],
        ["chemica:butene_bucket","C₄H₈","Alkene"],
        ["chemica:carbon_monoxide_bucket","CO","Inorganic Oxide"],
        ["chemica:chlorine_bucket","Cl₂","Halogen"],
        ["chemica:epichlorohydrin_bucket","C₃H₅ClO","Epoxide"],
        ["chemica:ethane_bucket","C₂H₆","Alkane"],
        ["chemica:fluorine_bucket","F₂","Halogen"],
        ["chemica:helium_bucket","He","Noble Gas"],
        ["chemica:light_hydrocarbons_bucket","C₃H₈ + C₄H₁₀","Alkanes"],
        ["chemica:methane_bucket","CH₄","Alkane"],
        ["chemica:nitrogen_bucket","N₂","Nonmetal"],
        ["chemica:nitrogen_dioxide_bucket","NO₂","Inorganic Oxide"],
        ["chemica:nitrous_oxide_bucket","N₂O","Inorganic Oxide"],
        ["chemica:oxygen_bucket","O₂","Nonmetal"],
        ["chemica:propene_bucket","C₃H₆","Alkene"],
        ["chemica:reformate_bucket","C₇H₈+","Aromatic Hydrocarbons Mix"],
        ["chemica:steam_bucket","H₂O","Inorganic Compound"],
        ["chemica:syngas_bucket","CO + H₂","Gas Mixture"],
        ["chemica:tungsten_hexafluoride_bucket","WF₆","Inorganic Halide"],
        ["chemica:vinyl_chloride_monomer_bucket","C₂H₃Cl","Organochloride"],
        ["chemica:biodiesel_bucket","C₁₈H₃₆O₂","Fatty Acid Methyl Ester"],
        ["chemica:ethanol_bucket","C₂H₅OH","Alcohol"],
        ["chemica:high_octane_gasoline_bucket","C₈H₁₈+","Hydrocarbon Blend"],
        ["chemica:hydrogen_fuel_bucket","H₂","Nonmetal"],
        ["chemica:ammonium_persulfate","(NH₄)₂S₂O₈","Inorganic Salt"],
        ["chemica:tungsten_carbide_dust","WC","Refractory Ceramic"],
        ["chemica:constantan_dust","Cu₅₅Ni₄₅","Metal Alloy"],
        ["chemica:caustic_soda_dust","NaOH","Inorganic Base"],
        ["chemica:electrum_grit","Ag + Au","Metal Alloy"],
        ["chemica:fluorite_dust","CaF₂","Halide Mineral"],
        ["chemica:phosphorus_dust","P₄","Nonmetal"],
        ["chemica:quartz_dust","SiO₂","Silicate Mineral"],
        ["chemica:rutile_dust","TiO₂","Oxide Mineral"],
        ["chemica:salt","NaCl","Inorganic Salt"],
        ["chemica:soda_ash","Na₂CO₃","Inorganic Salt"],
        ["chemica:sodium_bisulfate_dust","NaHSO₄","Inorganic Salt"],
        ["chemica:sodium_persulfate_dust","Na₂S₂O₈","Inorganic Salt"],
        // TFGM chemicals
        ["tfmg:ethylene_bucket", "C₂H₄", "Aliphatic Alkene"],
        ["tfmg:lpg_bucket", "C₃H₈ + C₄H₁₀", "Alkane Mixture"],
        ["tfmg:butane_bucket", "C₄H₁₀", "Alkane"],
        ["tfmg:propane_bucket", "C₃H₈", "Alkane"],
        ["tfmg:hydrogen_bucket", "H₂", "Nonmetal"],
        ["tfmg:furnace_bucket", "CO + CO₂ + N₂", "Low-Grade Fuel"],
        ["tfmg:propylene_bucket", "C₃H₆", "Alkene"],
        ["tfmg:neon_bucket", "Ne", "Noble Gas"],
        ["tfmg:carbon_dioxide_bucket", "CO₂", "Inorganic Oxide"],
        ["tfmg:air_bucket", "N₂ + O₂ + Ar + CO₂", "Gas Mixture"],
        ["tfmg:hot_air_bucket", "N₂ + O₂ + Ar + CO₂", "Thermal Gas Mixture"],
        ["tfmg:crude_oil", "Mixed Hydrocarbons", "Unrefined Fossil Fuel"],
        ["tfmg:diesel", "C₁₂H₂₃", "Heavy Fuel Oil"],
        ["tfmg:gasoline", "C₈H₁₈", "Light Fuel Oil"],
        ["tfmg:kerosene", "C₁₂H₂₆", "Jet Fuel"],
        ["tfmg:naphtha", "C₆H₁₄", "Light Hydrocarbon"],
        ["tfmg:heavy_oil", "C₂₀H₄₂", "Residual Fuel Oil"],
        ["tfmg:lubrication_oil", "C₂₅H₅₂", "Lubricant"],
        ["tfmg:cooling_fluid", "C₂H₆O₂", "Glycol"],
        ["tfmg:creosote_bucket","C₇H₈O₂","Phenolic Mixture"],
        ["tfmg:molten_steel_bucket","Fe + C","Metal Alloy"],
        ["tfmg:molten_slag_bucket","Ca₂MgSi₂O₇","Silicate Byproduct"],
        ["tfmg:molten_plastic_bucket","(C₃H₆)ₙ","Polyolefin"],
        ["tfmg:liquid_silicon_bucket","Si","Metalloid"],
        ["tfmg:napalm_bucket","C₈H₁₈ + Al/Mg-Soap","Incendiary Mixture"],
        ["tfmg:sulfuric_acid_bucket","H₂SO₄","Inorganic Acid"],
        ["tfmg:liquid_concrete_bucket","CaO·SiO₂ + H₂O","Hydrated Cement"],
        ["tfmg:liquid_asphalt_bucket","C₄₄H₅₀N₂O₂S","Bitumen"],
        // NorthStar chemicals
        ["northstar:liquid_oxygen_bucket","O₂","Nonmetal"],
    ]
    chemicals.forEach(([id, formula, category]) => {
        event.modify(id, tooltip => {
            tooltip.insert(1, Text.gold(`${formula}`));
            tooltip.insert(2, Text.gray(`${category}`));
        });
    });
})